name: Deploy

on:
  push:

jobs:
  deploy-staging:
    if: github.ref != 'refs/heads/main'
    runs-on: [self-hosted, docker]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm run build
      - run: docker compose up -d --force-recreate

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: [self-hosted, docker]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm run build
      - run: docker compose up -d --force-recreate
      - env:
          AWS_ACCESS_KEY_ID: ${{ secrets.LABODELUDO_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.LABODELUDO_S3_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: aws s3 sync dist/ s3://labodeludo.dev/ --delete
      - env:
          AWS_ACCESS_KEY_ID: ${{ secrets.LABODELUDO_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.LABODELUDO_S3_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: bash scripts/redirect-old-urls.sh
